name: "Castanets"
description: "Test"
author: "Team Castanets"
inputs:
  configPath:
    description: "Castanets config file path"
    default: "castanets.yml"
runs:
  using: "docker"
  image: "Dockerfile"
