name: "Castanets Core"
description: "Core"
author: "ScatterLab"
inputs:
  config-path:
    description: "Castanets Configuration File"
    default: "castanets.yml"
  token:
    description: "Github Personal Access Token"
runs:
  using: "composite"
  steps:
    - name: Download Last Artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ github.workflow }}
        github_token: ${{ inputs.token }}
        name: castanets
        search_artifacts: true
        check_artifacts: true
    - name: Castanets Core
      uses: ./core
      with:
        token: ${{ inputs.token }}
        config-path: ${{ inputs.config-path }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: castanets
        path: artifacts
