name: "Castanets"
description: "Test"
author: "Team Castanets"
inputs:
  config-path:
    description: "Castanets config file path"
    default: "castanets.yml"
  token:
    description: "Github Token"
runs:
  using: "docker"
  image: "../Dockerfile"
  args:
    - "--config-path"
    - ${{ inputs.config-path }}
  env:
    GITHUB_TOKEN: ${{ inputs.token }}
