name: Integration Test
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Test Run
        id: testrun
        uses: team-castanets/proof-of-concept@main
        with:
          configPath: castanets.yml
